[CONSTANTS]
water_density = {"value" = 1000.0, "units" = "kg/m^3"}
specificheat_water = {"value" = 0.0042, "units" = "MJ/kg*degC"}
specificheat_air = {"value" = 0.001013, "units" = "MJ/kg*degC"}
molecularweight = {"value" = 0.622, "units" = 'None'}
stefan_boltzman = {"value" = 4.9e-10, "units" = "MJ/m^2*K^4*day"}
absolute_zero = {"value" = 273.15, "units" = 'K'}
water_albedo = {"value" = 0.1, "units" = 'None'}  # after Zhao et al. 2019, 2022
timestep = {"value" = 1.0, "units" = 'days'}
emissivity_water = {"value" = 0.97, "units" = 'None'}
atmosphericP_sealevel = {"value" = 101.3, "units" = 'kPa'}

[GRIDMET]
GRIDMET_PARAMS = [
    'pr',
    'srad',
    'th',
    'tmmn',
    'tmmx',
    'vs',
    'vpd'
]
GRIDMET_BOUNDS = [-124.787500, 25.045833, -67.037500, 49.420833]
GRIDMET_NROWS = 585
GRIDMET_NCOLS = 1386
GRIDMET_XRES = 0.041666666666666664
GRIDMET_YRES = 0.04166666666666668

[DLEM]
INPUT_VARS = ['precip', 'solrad', 'lrad', 'vpd', 'wind_vel', 'LakeArea', 'LakeDepth', 'ftch_len']
DSET_COORDS = ['location', 'lat', 'lon', 'elev', 'time']